name = "processgroups"
version = "0.2.0"

description = "Process Groups for gleam"
gleam = ">= 1.4.0"
licences = ["Apache-2.0"]
links = [
  { title = "Gleam", href = "https://gleam.run" },
  { title = "Erlang Process Groups", href = "https://www.erlang.org/doc/man/pg.html" },
]
repository = { type = "github", user = "RudolfVonKrugstein", repo = "gleam_processgroups" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
